### Get all urls
GET {{url}}/url
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Get single url
GET {{url}}/url/B5xeQr
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Create Url
POST {{url}}/url
Accept: application/json
Content-Type:application/json
Authorization: Bearer {{jwt_token}}

{
  "longUrl": "http://youtube.com/"
}

### Delete Url
DELETE {{url}}/url/B5xeQr
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Update Long URL
PUT {{url}}/url/qCK6Qy
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "longUrl": "http://dr.dk/"
}