### Get all urls
GET {{url}}/urls
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Get single url
GET {{url}}/urls/B5xeQr
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Create Url
POST {{url}}/urls
Accept: application/json
Content-Type:application/json
Authorization: Bearer {{jwt_token}}

{
  "longUrl": "http://youtube.com/"
}

### Delete Url
DELETE {{url}}/urls/vsY3NU
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Update Long URL
PUT {{url}}/urls/qCK6Qy
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "longUrl": "http://dr.dk/"
}